### ISSUE TITLE
New Internship

### ISSUE THREAD

**Issue by mghanem8** [SimplifyJobs/Summer2024-Internships#2588]
### Link to Internship Posting

https://ats.rippling.com/rippling/jobs/eed09f08-a8b2-4d7c-8f8f-16402f3f4379

### Company Name

Rippling

### Internship Title

Software Engineer Intern

### Location

 New York, NY |  San Francisco, CA

### What term(s) is this internship offered for?

Summer 2024

### Does this internship offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

mghanem8@gatech.edu

**Comment by mghanem8** [comment]
Can you delete this issue please.

**Comment by novialriptide** [comment]
Issues cannot be deleted, only closed.

**Comment by mghanem8** [comment]
I do not want this on my github contributions. Why not delete it?
